name: Java Jar

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [19]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 18, 19]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 256

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Download JOSM custom jar
        id: download
        run: |
          mkdir -p libs
          curl -L -o libs/josm.jar "https://github.com/MarcelloPerathoner/josm/releases/latest/download/josm.jar"

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar

      - name: Generate release tag
        id: tag
        run: |
          echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: build/libs/*.jar
