name: Java Jar

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 21]

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Checkout Core
        run: |
          git clone --branch develop --depth=1 https://github.com/$GITHUB_REPOSITORY_OWNER/josm.git core
          echo "JOSM_DIR=$(pwd)/core" >> $GITHUB_ENV

      - name: Checkout Plugin
        run: |
          git clone --branch develop --depth=1 https://github.com/$GITHUB_REPOSITORY.git plugin
          echo "PLUGIN_DIR=$(pwd)/plugin" >> $GITHUB_ENV

      - name: Build Core
        run: |
          cd $JOSM_DIR
          ./gradlew jar

      - name: Build Plugin
        run: |
          cd $PLUGIN_DIR
          ./gradlew jar sourcesJar javadocJar

      - name: Generate release tag
        id: tag
        run: |
          echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Generate MANIFEST
        id: manifest
        run: |
          cd $PLUGIN_DIR
          python $JOSM_DIR/scripts/manifest.py --icons --root-dir build/libs *.jar > build/libs/MANIFEST

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            ${{ env.PLUGIN_DIR }}/build/libs/*.jar
            ${{ env.PLUGIN_DIR }}/build/libs/MANIFEST
